myblogsite/blog/urls.py
from django.urls import path, include
from . import views

app_name='blog'

urlpatterns = [
    path('',views.PostListView.as_view(),name='post_list'),
    path('about/',views.AboutView.as_view(),name='about'),
    path('post/<int:pk>/',views.PostDetailView.as_view(),name='post_detail'),
    path('post/new/',views.CreatePostView.as_view(),name='post_new'),
    path('post/<int:pk>/edit/',views.PostUpdateView.as_view(),name='post_edit'),
    path('post/<int:pk>/remove/',views.PostDeleteView.as_view(),name='post_remove'),
    path('drafts/',views.DraftListView.as_view(),name='post_draft_list'),
    path('post/<int:pk>/comment/',views.add_comment_to_post,name='add_comment_to_post'),
    path('comment/<int:pk>/approve/',views.comment_approve,name='comment_approve'),
    path('comment/<int:pk>/remove/',views.comment_remove,name='comment_remove'),
    path('post/<int:pk>/publish/',views.post_publish,name='post_publish'),
]

myblogsite/myblogsite/urls.py
from django.contrib import admin
from django.urls import path,include # include is used to include urls from other apps

from django.contrib.auth import views # this is used to import the views for login and logout from auth app in django

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('blog.urls'),name='blog'),
    path('accounts/login/',views.LoginView.as_view(),name='login'),
    path('accounts/logout.html',views.LogoutView.as_view(),name='logout',kwargs={'next_page':'/'}), # kwargs is used to pass arguments to the view
    # next_page is used to redirect the user to the home page after logout
]

myblogsite/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
# reverse() is a function that returns the URL for a given view and optional parameters.


# Create your models here.
class Post(models.Model):
    # author is actually connected to the auth.User model ie superuser
    # each author will be linked to a single post
    # foreign key actually links to another model and the 'auth.User' is the application name and the model name
    author=models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title=models.CharField(max_length=200)
    text=models.TextField()
    created_date=models.DateTimeField(default=timezone.now)
    published_date=models.DateTimeField(blank=True, null=True)
    # published date can be blank and null because we don't want to publish the post right away.
    # blank=True means that the field is optional and null=True means that the database column will be null.

    def publish(self):
        self.published_date=timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)
        # this is a query set that will return only the approved comments

    def get_absolute_url(self): # name of function is important as it is predefined  by Django
        return reverse('blog:post_detail',kwargs={'pk':self.pk})
        # post_detail is the name of the view that we want to redirect to
        # kwargs is a dictionary that maps the pk variable from urls.py to the pk of the current post

    def __str__(self):
        return self.title


class Comment(models.Model):
    # each comment will be linked to a single post

    # foreign key actually links to another model and the 'blog.Post' is the application name and the model name
    post=models.ForeignKey('blog.Post',related_name='comments',on_delete=models.CASCADE)
    author=models.CharField(max_length=200)
    text=models.TextField()
    created_date=models.DateTimeField(default=timezone.now)
    approved_comment=models.BooleanField(default=False)

    def approve(self):
        self.approved_comment=True
        self.save()


    # it tells Django where to go when we create a new comment i.e. where website should redirect us
    def get_absolute_url(self): # name of function is important as it is predefined  by Django
        return reverse('post_list')

    def __str__(self):
        return self.text

myblogsite/blog/forms.py
from django import forms
from blog.models import Post,Comment

class PostForm(forms.ModelForm):

    class Meta:
        model=Post
        # fiels is a tuple of fields that we want to include in our form
        fields=('author','title','text')

        # widgets is a dictionary of fields that we want to style
        # connectng specific widgets to specific styling
        widgets={
            'title':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }

class CommentForm(forms.ModelForm):

    class Meta:
        model=Comment
        # field is a tuple of fields that we want to include in our form
        fields=('author','text')

        # widgets is a dictionary of fields that we want to style
        # connecting specific widgets to specifying style
        widgets={
            'author':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea'})
        }

myblogsite/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import (TemplateView,ListView,DetailView,
                                  CreateView,UpdateView,DeleteView)
from  blog.models import Post,Comment
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from blog.forms import PostForm,CommentForm

# Create your views here.
class AboutView(TemplateView):
    template_name='about.html'

class PostListView(ListView):
    model=Post

    def get_queryset(self):
        # this allows me to use django's ORM to query the database
        # __lte is a field lookup that means less than or equal to
        # -published_date means order by published date in descending order
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')


class PostDetailView(LoginRequiredMixin,DetailView):
    model=Post


class CreatePostView(LoginRequiredMixin,CreateView):
    login_url='/login/'
    redirect_field_name='blog/post_detail.html'
    form_class=PostForm
    model=Post

class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url='/login/'
    redirect_field_name='blog/post_detail.html'
    form_class=PostForm
    model=Post


class PostDeleteView(LoginRequiredMixin,DeleteView):
    model=Post
    success_url=reverse_lazy('blog:post_list')
    # reverse_lazy is used because we don't want to execute the reverse function until the post is deleted

class DraftListView(LoginRequiredMixin,ListView):
    login_url='/login/'
    redirect_field_name='blog/post_list.html'
    model=Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('created_date')
        # __isnull is a field lookup that means is null ie post is not published yet
        # order by created date in ascending order


##############################################################################################################
'''
Now we need to create the views for the comments.
These are functional views 
They will be called when the user wants to approve or remove a comment
'''
##############################################################################################################



@login_required
def post_publish(request,pk):
    post=get_object_or_404(Post,pk=pk) # this is how we get the post that we want to publish
    post.publish() # this is how we publish the post
    return redirect('blog:post_detail',pk=pk) # redirect to the post detail page


@login_required
def add_comment_to_post(request,pk):
    post=get_object_or_404(Post,pk=pk) # this is how we get the post that we want to comment on
    if request.method=='POST': # if the form is submitted
        form=CommentForm(request.POST) # create a form instance with the submitted data
        if form.is_valid(): # check if the form is valid
            comment=form.save(commit=False) # create a comment object but don't save it to the database yet
            comment.post=post # this is how we connect the comment to the post
            comment.save() # save the comment to the database
            return redirect('blog:post_detail',pk=pk) # redirect to the post detail page
    else:  # agr form submit ni hua hai to form bnao aur dobara render kro
        form=CommentForm() # if the form is not valid then create a new form
    return render(request,'blog/comment_form.html',{'form':form}) # render the form again


@login_required
def comment_approve(request,pk):
    comment=get_object_or_404(Comment,pk=pk) # this is how we get the comment that we want to approve
    comment.approve() # approve the comment
    return redirect('blog:post_detail',pk=comment.post.pk) # redirect to the post detail page


@login_required
def comment_remove(request,pk):
    comment=get_object_or_404(Comment,pk=pk) # this is how we get the comment that we want to remove
    post_pk=comment.post.pk # get the pk of the post that the comment belongs to
    comment.delete() # delete the comment
    return redirect('blog:post_detail',pk=post_pk) # redirect to the post detail page

myblogsite/blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block content %}
    <h1>About Post...</h1>
    <p>Thanks for checking</p>
{% endblock content %}

myblogsite/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BLOG</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Medium Style Editor -->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <!-- Custom CSS -->
<!--    <link rel="stylesheet" href="{% static 'css/blog.css' %}">-->


    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barrio&display=swap" rel="stylesheet">


</head>
<body class="loader">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blog:post_list' %}">BLOG</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'blog:about' %}">About</a>
                <a class="nav-link" href="https://github.com/udaysingh21">GitHub</a>
                <a class="nav-link" href="https://www.linkedin.com/in/uday-vikram-singh-756baa20b/">Linkedin</a>
            </div>

            {% if user.is_authenticated %}
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:post_new' %}">New Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:post_draft_list' %}">Drafts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                    </li>
                    <li class="nav-item">
                        <span class="nav-link">Welcome: {{ user.username }}</span>
                    </li>
                </ul>
            {% else %}
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </li>
                </ul>
            {% endif %}
        </div>
        </div>
    </nav>


    <!-- Main Content -->
    <div class="content-container">
        <div class="row">
            <div class="col-md-8">
                <div class="blog_posts">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
    </div>

</body>
</html>

myblogsite/blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% block content %}

<h1>New Comment</h1>
<form class="post-form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default" name="button">Save</button>
</form>

<script>
var editor = new MediumEditor('.editable');
</script>

{% endblock content %}

myblogsite/blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ post.title }}"?</p>
    <button type="submit" class="btn btn-danger">Yes</button>
    <a href="{% url 'blog:post_detail' post.pk %}" class="btn btn-default">No</a>
</form>

{% endblock content %}

myblogsite/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}

<h1 class="postitle loader">{{post.title}}</h1>
{% if post.published_date %}
     <div class="date postdate">
         {{ post.published_date|date:"d-m-Y" }}
     </div>
{% else %}
        <a class="btn btn-primary" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
{% endif %}

<p class="postcontent">{{ post.text|safe|linebreaksbr}}</p>

{% if user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk %}">
        <span class="glyphicon glyphicon-pencil"></span>
    </a>

    <a class="btn btn-danger" href="{% url 'blog:post_remove' pk=post.pk %}">
        <span class="glyphicon glyphicon-trash"></span>
    </a>
{% endif %}

<hr>
<a charset="btn btn-primary comment" href="{% url 'blog:add_comment_to_post' pk=post.pk %}" class="btn btn-primary">Add Comment</a>

<div class="container">
    {% for comment in post.comments.all %}
    <br>
    {% if user.is_authenticated or comment.approved_comment%}
        {{ comment.created_date }}
        {% if not comment.approved_comment %}
             <a class="btn btn-primary comment" href="{% url 'blog:comment_remove' pk=comment.pk %}">
                <span class="glyphicon glyphicon-trash"></span>
            </a>

            <a class="btn btn-primary comment" href="{% url 'blog:comment_approve' pk=comment.pk %}">
                <span class="fa-duotone fa-check"></span>
            </a>
        {% endif %}

        <p>{{ comment.text|safe|linebreaks }}</p>
        <p>Posted by: {{ comment.author }}</p>
    {% endif %}
    {% empty %}
        <p>No comments here yet :(</p>

    {% endfor %}

</div>


{% endblock content %}

myblogsite/blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}
{% block content %}

{% for post in posts %}

    <div class="post">
        <p class="date">Created on: {{ post.created_date|date:"d-m-Y" }}</p>
        <h1><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h1>
        <p>{{ post.text|truncatechars:200}}</p>
    </div>

{% endfor %}


{% endblock content %}

myblogsite/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% block content %}

<h1>New Post</h1>
<form class="post-form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
</form>

<script>
var editor = new MediumEditor('.editable');
</script>

{% endblock content %}

myblogsite/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}

<div class="centerstage">
    {% for post in post_list %}
    <div class="post">
        <h1>
            <a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a>
        </h1>

        <div class="date">
            <p>Published on: {{ post.published_date|date:"d-m-Y" }}</p>
        </div>

        <a href="{% url 'blog:post_detail' post.pk %}">
            Comments: {{ post.comments.count }}
        </a>

    </div>
    {% endfor %}
</div>

{% endblock content %}